package com.yann.smart_valuator_api.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity representing a single item valuation request and its AI-generated result.
 * Maps to the {@code estimations} table in PostgreSQL.
 */
@Entity
@Data
@Table(name = "estimations")
public class Estimation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the item being valued (e.g. "iPhone 14 Pro"). Required. */
    @Column(name = "item_name", nullable = false)
    private String itemName;

    /** Product category (e.g. "Smartphone", "Laptop"). Optional. */
    @Column(name = "category")
    private String category;

    /** Brand of the item (e.g. "Apple", "Samsung"). Optional. */
    @Column(name = "brand")
    private String brand;

    /** Year the item was originally purchased. Required. */
    @Column(name = "year", nullable = false)
    private Integer year;

    /** Item condition on a scale of 1 (poor) to 10 (mint). */
    @Column(name = "condition_rating")
    private Integer conditionRating;

    /** AI-estimated resale price in EUR. Null if estimation failed. */
    @Column(name = "estimated_price", precision = 10, scale = 2)
    private BigDecimal estimatedPrice;

    /** Natural language description generated by the AI model. */
    @Column(name = "ai_description", columnDefinition = "TEXT")
    private String aiDescription;

    /** Timestamp of when this estimation was created. Set automatically before insert. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Sets {@code createdAt} to the current time before the first database insert,
     * if it has not already been set manually.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}